services:
    webserver:
        container_name: sport-teams-nginx
        restart: on-failure
        image: 'nginx:alpine'
        ports:
            - '8000:80'
        volumes:
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './public:/application/public'
    php-fpm:
        container_name: sport-teams-php-fpm
        restart: on-failure
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
            target: development
        volumes:
            - '.:/application'
        working_dir: /application
        environment:
            XDEBUG_MODE: 'debug,develop'
        extra_hosts:
            - host.docker.internal:host-gateway
    db:
        container_name: sport-teams-db
        image: mariadb
        volumes:
            - sport-teams-db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_USER: user
            MYSQL_PASSWORD: 1234
        ports:
            - '33061:3306'
    phpmyadmin:
        depends_on:
            - db
        container_name: sport-teams-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8001:80'
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=300000000
            - MYSQL_ROOT_PASSWORD=1234
            - PMA_HOST=db
volumes:
    sport-teams-db-data:
